s="""☐ Basic Functionalities: [Also have the functionalities for `reading` and `deleting` all the data from a given table (admin level only)]
☐      01. Branch                        -        CRU   one   (+R All)
☐      02. Bank_Account                  -        CRU   one   (+R Some)    (+close/open account)
☐      03. Department                    -        CRUD  one   (+R All)
☐      04. Employee                      -        CRUD  one   (+R Some)
☐      05. Branch_Managed_By             -        CRU   one   (+R Some)
☐      06. Customer                      -        CRU   one   (+R Some)
☐      07. Customer_Phone_Number         -        CRD   one   (+R Some)
☐      08. Collateral                    -        CRUD  one   (+R Some)
☐      09. Documents_Link                -        CRUD  one   (+R Some)
☐      10. Personal_Customer             -        CRU   one   (+R Some)
☐      11. Business_Customer             -        CRU   one   (+R Some)
☐      12. Savings_Account               -        CRU   one   (+R Some)    (+close/open account)
☐      13. Current_Account               -        CRU   one   (+R Some)    (+close/open account)
☐      14. Minor_Account                 -        CRU   one   (+R Some)    (+close/open account)
☐      15. Zero_Balance_Account          -        CRU   one   (+R Some)    (+close/open account)
☐      16. Card                          -        CRU   one   (+R Some)    (+block/unblock card)
☐      17. Debit_Card                    -        CRU   one   (+R Some)    (+block/unblock card)
☐      18. Prepaid_Card                  -        CRU   one   (+R Some)    (+block/unblock card)
☐      19. ATM_Card                      -        CRU   one   (+R Some)    (+block/unblock card)
☐      20. Credit_Card                   -        CRU   one   (+R Some)    (+block/unblock card)
☐      21. Account_Linked_Credit_Card    -        CRU   one   (+R Some)    (+block/unblock card)
☐      22. Loan                          -        CRU   one   (+R Some)
☐      23. Collateral_Loan               -        CRU   one   (+R Some)
☐      24. Non_Collateral_Loan           -        CRU   one   (+R Some)
☐      25. Documents_PDF                 -        CRUD  one   (+R Some)
☐      26. Loan_Account                  -        CRU   one   (+R Some)    (+close/open account)
☐      27. Insurance                     -        CRU   one   (+R Some)
☐      28. Asset_Insurance               -        CRU   one   (+R Some)
☐      29. Loan_Protection_Insurance     -        CRU   one   (+R Some)
☐      30. Term_Life_Insurance           -        CRU   one   (+R Some)
☐      31. Medical_Insurance             -        CRU   one   (+R Some)
☐      32. Transaction_Details           -        CRU   one   (+R Some)
☐      33. Passbook                      -        CRU   one
☐      34. UPI                           -        CRU   one   (+R Some)
☐      35. UPI_Transactions              -        CRU   one   (+R Some)
☐      36. Bill_Payment                  -        CRUD  one
☐      37. Card_Transactions             -        CRU   one   (+R Some)
☐      38. Auto_Payment                  -        CRUD  one   (+R Some)
☐      39. Auto_Payment_Loan             -        CRUD  one   (+R Some)
☐      40. Auto_Bill_Payment             -        CRUD  one   (+R Some)
☐      41. Transaction_Log               -        CR    one   (+D All)
☐      42. Ad_Channel                    -        CRUD  one   (+R All)
☐      43. Advertisement                 -        CRUD  one   (+R Some)
☐      44. User_Credentials              -        CRU   one
☐      45. Employee_Credentials          -        CRU   one
☐      46. Fixed_Deposit                 -        CRUD  one   (+R Some)
☐      47. Recurring_Deposit             -        CRUD  one   (+R Some)
☐      48. Chequebook                    -        CR    one
☐      49. Bank_Statement                -        CR    one   (+R Some)
☐      50. OTPs                          -        CR    one   (+D All)
☐      51. Installment                   -        CRU   one   (+R Some)
☐      52. Closed_Account                -        CRD   one
☐      53. Blocked_Card                  -        CRD   one"""

print(s)